name: Sync labels
on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a
        with:
          delete-other-labels: true
          config-file: 'https://raw.githubusercontent.com/TavstalDev/.github/refs/heads/main/.github/labels-config.yml'
